# permissions for end users to edit memcached2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: multi
    app.kubernetes.io/managed-by: kustomize
  name: cache2-memcached2-editor-role
rules:
- apiGroups:
  - cache2.example.com
  resources:
  - memcached2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache2.example.com
  resources:
  - memcached2s/status
  verbs:
  - get
